{
 "title": "HW1 Business metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "/api/orders status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\", path=\"/api/orders\", status=~\"2..\"}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\", path=\"/api/orders\", status=~\"4..\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\", path=\"/api/orders\", status=~\"5..\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "/api/users status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\", path=\"/api/users\", status=~\"2..\"}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\", path=\"/api/users\", status=~\"4..\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_requests_total{method=\"POST\", path=\"/api/users\", status=~\"5..\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "/api/orders latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{path=\"/api/orders\", status=~\"2..\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{path=\"/api/orders\", status=~\"2..\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{path=\"/api/orders\", status=~\"2..\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "/api/users latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{path=\"/api/users\", status=~\"2..\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{path=\"/api/users\", status=~\"2..\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{path=\"/api/users\", status=~\"2..\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}